### ISSUE TITLE
Sprint 3 : Generic method for third party calls and db logging

### ISSUE THREAD

**Issue by ShaikhInaam** [ShaikhInaam/servicemarket-be#10]
create a generic method for sending third party requests
Separate method for post requests
separate method for Get requests

that will use RestTemplate to send request(Generic Object) to third party APIs and retun an Object of response
Create a db table by adding into liquibase
Transaction logger BE
Columns : id, transaction id, request json, response json, time

and log request sent to third party and response came from third party

**Comment by HassanWarisMahar** [comment]
Knowledged

**Comment by ShaikhInaam** [comment]
11/11/2020 : Wednesday

**Comment by ShaikhInaam** [comment]
PR generted
